### ISSUE TITLE
一阶段超时问题

### ISSUE THREAD

**Issue by fdx321** [Dromara/Raincat#8]
consume 调 Order和Stock两个服务，一阶段调用Order超时，consume自己回滚本地事务，并通知TM回滚全局事务。TM通知Order回滚，但这个时候Order的异步线程还没有await，自然也就没有TM唤起来做rollback. Order的本地事务就一直悬挂在那里了。

**Comment by fdx321** [comment]
我看事务补偿，只有在全局事务组是COMMIT状态的时候才补偿，不是的话就删除补偿记录。那么针对我说的这种场景，是否可以在补偿的时候做rollback呢

**Comment by yu199195** [comment]
一阶段超时的时候，是不会今天提交的。。现在数据一致吗？

**Comment by fdx321** [comment]
没有明白你说的问题。我觉得我说的场景是会造成Order事务悬挂的（我也测试过），这个时候悬挂的事务打算怎么处理呢？人工介入吗？
